### ISSUE TITLE
Deploy command

### ISSUE THREAD

**Issue by LSnyd** [NVIDIA/NVFlare#110]
Hi there, 

when I tried to get hello-monai deployed with `deploy_app hello-monai` as stated in the README, I get an error. 
It works, if I add either client or server behind the command: 

`deploy_app hello-monai server` 
or 
`deploy_app hello-monai client`

**Comment by nvkevlu** [comment]
Thank you for noting this, the `deploy_app` command does require a target to be specified. In most examples we have `deploy_app [app_name] all`, but the target is missing in the README. We will update the README to correct this.
