### ISSUE TITLE
[BUG] Command "nvflare" not found 

### ISSUE THREAD

**Issue by hackenjoe** [NVIDIA/NVFlare#1182]
Unfortunately I can't run nvflare on Ubuntu because it tells me that the command (`nvflare simulator -h`) is not found. Even if I use the Docker solution. Inside the docker it also shows "command not found". Thus unable to run local experiments.

I tried the MWE from https://nvflare.readthedocs.io/en/2.2.1/getting_started.html

Used OS: Ubuntu 18.04.5 LTS

**Comment by yhwen** [comment]
Hi @hackenjoe Could you please provide which version of NVFlare are you using? Did you install the NVFlare using "pip"? And did you run the command in a virtual environment?

**Comment by hackenjoe** [comment]
Sure, I use the newest versions. And I installed nvflare using pip running in a new conda environment.

`Name: nvflare
Version: 2.1.2
Summary: Federated Learning Application Runtime Environment
Home-page: https://github.com/NVIDIA/NVFlare
Author: 
Author-email: 
License: 
Location: /opt/conda/lib/python3.8/site-packages
Requires: cryptography, flask, google-api-python-client, grpcio, gunicorn, numpy, psutil, PyYAML, tenseal
Required-by: `

But as mentioned previously, I am using the docker container and inside the container it says that the package is already be installed but yet, the command is not found.

`bash: nvflare: command not found`

**Comment by andreaskopp** [comment]
I have the same issue using the docker container following the Getting Started instructions:
https://nvflare.readthedocs.io/en/2.2.1/getting_started.html
@hackenjoe - as this bug is "closed": do you have a solution to share? Thank you!

**Comment by YuanTingHsieh** [comment]
@andreaskopp thanks for your interest and question.

I've noticed that our https://nvflare.readthedocs.io/en/2.2.1/getting_started.html needs to be updated.

Please use the following Dockerfile for building the docker image:

```Dockerfile
ARG PYTORCH_IMAGE=nvcr.io/nvidia/pytorch:22.12-py3
FROM ${PYTORCH_IMAGE}

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install nvflare

WORKDIR /workspace/
RUN git clone https://github.com/NVIDIA/NVFlare.git --branch 2.2 --single-branch NVFlare


```
