### ISSUE TITLE
'setsid' error

### ISSUE THREAD

**Issue by pygabc1** [NVIDIA/NVFlare#1189]
When I run [nvflare simulator path.../NVFlare/examples/hello-numpy-sag/app -w /tmp/nvflare/workspace_folder/ -n 8 -t 1] in gitbash, I confront the error of 

> [ERROR - run_client_thread error: module 'os' has no attribute 'setsid']

How to fix it? Thanks.

**Comment by yhwen** [comment]
@pygabc1 Could you please let us know which environment were you running the "nvflare simulator ..." command? Were you running in a Linux system? or a Windows system? or Mac OS?

**Comment by Chesterguan** [comment]
hi I could provide more information based on this issue. 

The problem is triggered by `Windows` OS.  I don't think there is a way to solve the problem.

**Comment by YuanTingHsieh** [comment]
As far as I know, currently we are not planning to support Windows, we might support it in the future.
