### ISSUE TITLE
Potential bug in SVT?

### ISSUE THREAD

**Issue by LSnyd** [NVIDIA/NVFlare#1214]
Hi all, 
is this intended that in [line 103](https://github.com/NVIDIA/NVFlare/blob/e5e8c15a3455c81cb16268fbaafeef3f26d2b195/nvflare/app_common/filters/svt_privacy.py#L103) of the SVTPrivacy class, only a random choice of the accepted parameters is taken with replacement? This will lead to a lower number of accepted and candidate parameters ([Line 108](https://github.com/NVIDIA/NVFlare/blob/e5e8c15a3455c81cb16268fbaafeef3f26d2b195/nvflare/app_common/filters/svt_privacy.py#L108)) than originally computed. 

So even if I am running SVT it with a fraction of 1.0, not all of my noisy values (3.491.530) are transferred, but around 1.284.489 of them are set to 0.

**Comment by YuanTingHsieh** [comment]
Thanks for tagging me, @holgerroth and @ZiyueXu77 can you check if the logic is intended as pointed out by @LSnyd ?
Thanks

**Comment by wyli** [comment]
Thanks for reporting, what would be the expected behaviour in this case for your experiments?

**Comment by LSnyd** [comment]
Hi @wyli,
I would expect that if I am adding SVT with a fraction of 1.0 that all of my noisy values (3.491.530) are transferred. Instead, around 1.284.489 of them are set to 0 due to the random choice with replacement.

**Comment by wyli** [comment]
thanks, I've created a patch to make it optional https://github.com/NVIDIA/NVFlare/pull/1224.

**Comment by LSnyd** [comment]
Why should this ever be set to true though? I believe this breaks the whole SVT functionality.

**Comment by wyli** [comment]
I'm not sure how this will affect any existing workflows, so keep the default to the same as the previous versions. happy to change the default value whenever we see a clear advantage.

**Comment by LSnyd** [comment]
I will try to explain myself in the following. Let's say our network has 100 parameters and we set the SVT fraction to 1.0
When we arrive at line 103, the random.choice function will cause that we most likely will end up with a collection of parameters that includes duplicates (e.g. 30 duplicates). As replace=True means that we can select elements twice. 

When we arrive in line [108](https://github.com/NVIDIA/NVFlare/blob/e5e8c15a3455c81cb16268fbaafeef3f26d2b195/nvflare/app_common/filters/svt_privacy.py#L108), we will take the set of the accepted parameters, which removes all duplicates. At this point, the number of accepted parameters may be 70 for instance, and not 100 as we would expect with a fraction of 1.0. Finally, in the same line, we are computing the total amount of parameters whose noisy values will not be transferred. When the amount of accepted parameters (without duplicates) is now 70, the amount of untransferred parameters will be 30. These 30 parameters are set to 0.0 in line 109 and their noisy values will not be transferred, even though we have a SVT fraction of 1.0. 

Does that make sense?

**Comment by holgerroth** [comment]
Thank you for raising this issue, @LSnyd. Using the `replace=False` option provided by @wyli should allow you to achieve your desired behavior. In order to don't change the behavior of this filter for existing users, we will keep the default setting as is for now.

**Comment by LSnyd** [comment]
Okay, thank you @holgerroth. Do you agree though that `replace=False` should be the default behavior?
So you are waiting for a new update of NVFlare to include this change or is there any reason why this should be set to true that I am not aware of?

**Comment by LSnyd** [comment]
From the description of "replace" in the [NumPy documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html), I understand that
`replace=True` allows to sample the same parameter twice. Hence, when we, later on, take the set() of the sampled parameters, which only keeps unique values, we end up with a number of parameters somewhere between 1 and n_upload parameters.

`replace=False` will not allow to sample the same parameter twice. Therefore we would also after creating the set() end up with n_upload parameters. 

Here is as well a toy example: 

```
import numpy as np

temp = [1,2,3,4,5,6,7,8,9,10]

temp_sampled_w_replacement = np.random.choice(temp, size=len(temp), replace=True)
temp_sampled_w_o_replacement = np.random.choice(temp, size=len(temp), replace=False)

print("Set after sampling with replacement", set(temp_sampled_w_replacement))
print("Set after sampling without replacement", set(temp_sampled_w_o_replacement))
```

```
Output: 

Set after sampling with replacement {2, 4, 5, 6, 8, 10}
Set after sampling without replacement {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
```
