### ISSUE TITLE
[BUG] Dashboard - Cannot set num GPUs to 0

### ISSUE THREAD

**Issue by parkeraddison** [NVIDIA/NVFlare#1216]
**Describe the bug**
While using the Dashboard as an Org Admin and attempting to configure client sites, you cannot set NUM GPUS to 0. Attempting to do so returns the value to 4. The minimum positive value you can set is 1.

This causes sites without GPUs to fail their resource policies. To allow a non-GPU client to launch, the local/resources.json.default must be manually modified or overwritten in the downloaded site startup kit.

Negative values for num GPUs are also strangely accepted.

**To Reproduce**
1. Go to dashboard
2. Log in or register as an Org Admin
3. On post-registration page or "MY INFO" page, click "Add Site"
4. Double click the new site's "NUM GPUS" entry and enter 0
5. Click elsewhere and notice that the value returns to 4
6. Try again, this time enter a value of -1
7. Click elsewhere and notice the negative value is accepted

**Expected behavior**
The NUM GPUS value should accept a value of zero (most important), and reject negative values (style points).

**Screenshots**
![numgus](https://user-images.githubusercontent.com/33291380/211440269-6a4e88d2-a16d-4814-842c-18db52f33935.gif)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Python Version: 3.8.12
 - NVFlare Version: 2.2.1

**Additional context**
Running the dashboard using the current Docker image at nvflare/nvflare, with the command:
`nvflare dashboard -p 8008 --start`

**Comment by nvkevlu** [comment]
Thank you for noting this, I will take a look into this and make some improvements.

**Comment by YuanTingHsieh** [comment]
it is fixed by @nvkevlu it will be in next release of dsahboard.
