### ISSUE TITLE
Preflight check - support for DummyOverseerAgent?

### ISSUE THREAD

**Issue by parkeraddison** [NVIDIA/NVFlare#1220]
**Is your feature request related to a problem? Please describe.**
I noticed while provisioning a project with a DummyOverseerAgent that the preflight checks fail with the message *"Exception happens in checking: overseer agent nvflare.ha.dummy_overseer_agent.DummyOverseerAgent is not supported., this package is not in correct format."*

This is due to the following code
https://github.com/NVIDIA/NVFlare/blob/b4ce3a8faec19363574fb619329668b5cf926490/nvflare/tool/package_checker/utils.py#L95-L96
https://github.com/NVIDIA/NVFlare/blob/b4ce3a8faec19363574fb619329668b5cf926490/nvflare/tool/package_checker/package_checker.py#L87-L92

**Describe the solution you'd like**
I feel like it's still useful for the preflight checks to run the rest of their tests even if a DummyOverseer is used; e.g. the server should still check its port bindings, storage, and dry run; and the clients and consoles should still check that they can connect to the server and dry run.

Would it be possible to support the DummyOverseerAgent in the preflight checks? 

**Describe alternatives you've considered**
For a quick-patch, could the preflight check could just ignore any overseer-related checks if a DummyOverseer is being used? And carry on with the rest of the checks rather than throwing an exception?

**Additional context**
N/A

**Comment by YuanTingHsieh** [comment]
Fixed in #1234
