### ISSUE TITLE
Tenseal dependency for HE is not available on ARM aarch64

### ISSUE THREAD

**Issue by kkersten** [NVIDIA/NVFlare#130]
The tenseal dependency is not available for the ARM aarch64 platform, causing installation to fail.  This has been reported for local development on Mac M1 and will affect other non-x86 architectures, Jetson, Clara AGX, IBM POWER, etc..

The tenseal dependency is only required when using the HEBuilder module, and it looks like all other functionality could be used without this dependency.  Can tenseal be made optional, with the caveat that HE is not available without tenseal?

One option would be providing an alternate install, a `requirements-no-tenseal.txt` that includes everything but tenseal.  For example, I generated this file in a clean venv on my linux machine using:
```
pip download nvflare -d /tmp -v \
    | grep Collecting \
    | awk '{print $2}' \
    | tr '[:upper:]' '[:lower:]' \
    | grep -v tenseal \
    | tee requirements-no-tenseal.txt
```
and verified that I can install nvflare and all deps except tenseal by copying to an aarch64 system (in this case a Jetson TX2) with:
```
python3 -m pip install --no-deps -r requirements-no-tenseal.txt
```

This is a pretty awkward solution.  It would be much cleaner to remove the tenseal dependency in the default packaging, since HE is optional, and note in the docs that tenseal must be installed when using HE.

**Comment by taleinat** [comment]
It's possible to make homomorphic encryption support an [optional feature](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies), with its dependencies only installed it it is specific explicitly using e.g. `pip install nvflare[he]`.

**Comment by siomvas** [comment]
This issue remains, current version (2.2.0) has no optional features and tenseal is necessary, making installation impossible on Apple Silicon,

**Comment by taleinat** [comment]
Can confirm, this is fixed on the main branch but somehow that didn't make it into 2.2.0.
