### ISSUE TITLE
Dashboard UI not generating server and client startup packages.

### ISSUE THREAD

**Issue by chanfm81** [NVIDIA/NVFlare#1317]
Hi,

I have created an empty folder and started the dashboard UI according to the link https://nvflare.readthedocs.io/en/main/user_guide/dashboard_api.html.
e.g. nvflare dashboard -p 8080 --start

In the project admin role, I navigated to browser at localhost:8080 and keyed in the server name without HA and made the project public.
After that, I signed up with an org admin role in which the org admin role created 2 client sites.
Back to the admin role, I approved the org admin role, 2 client sites and freezed the project.
However in the Download tab, the admin role is able to download the admin console package but not the server startup package even though it promoted a password to decrypt the zip file.

I am not sure if I have missed any of the above steps.

For your advice.
Thanks.

**Comment by IsaacYangSLA** [comment]
Your steps are correct.  We also observed the same issue.  This will be fixed in #1330.
