### ISSUE TITLE
job folder not in client transfer folder when submit_job command is issued

### ISSUE THREAD

**Issue by chanfm81** [NVIDIA/NVFlare#1336]
Hi,

I tried to put hello-pt example from v2.2 into the transfer folder of the lead researcher (https://github.com/NVIDIA/NVFlare/tree/2.2/examples/hello-pt) 
e.g. **"flare_lead/scientist \@test.com/transfer/hello-pt"** directory
Then I use the command line to issue "submit_job hello-pt"

I noticed the job folder on client side is appearing at the root folder **"flare_client1/flclient1/"** and not in **"flare_client1/flclient1/transfer"** folder.

I am simulating real world example of 1 server and 2 clients on same machine using /etc/hosts

Is it due to custom code for the hello-pt example?

Also the hello-pt example ends with a non zero return code
"
2023-02-10 17:02:44,765 - ClientRunner - INFO - [identity=flclient1, run=f9b0d6e7-e1ac-4d0a-b99e-7e457a4e12bf]: END_RUN fired
2023-02-10 17:02:44,766 - FederatedClient - INFO - Shutting down client: flclient1
**2023-02-10 17:02:45,379 - ProcessExecutor - INFO - run (f9b0d6e7-e1ac-4d0a-b99e-7e457a4e12bf): child worker process finished with execution code: -9**
"

For your advice.
Thanks.

**Comment by YuanTingHsieh** [comment]
Hi @chanfm81 thanks for the question.

For NVFlare 2.2.x, the job is submitted to the NVFlare server.
If you use admin command "list_jobs" you should be able to see the job id of that submitted job.

If the job is ready to deploy and run, the NVFlare server will then deploy the corresponding apps into each sites.
Those apps will be put inside [site-1]/[job id], so no longer inside the [site-1]/[transfer] folder anymore.

Please refer to the documentation for concepts of jobs and apps: https://nvflare.readthedocs.io/en/latest/real_world_fl/job.html

-------------------------------------------------

As for the message: `2023-02-10 17:02:45,379 - ProcessExecutor - INFO - run (f9b0d6e7-e1ac-4d0a-b99e-7e457a4e12bf): child worker process finished with execution code: -9`.
That is also normal, @yhwen and I will make sure to improve that text in the next release.

**Comment by chanfm81** [comment]
Hi,

Thanks for the reply.

I refer to the sentence "Those apps will be put inside [site-1]/[job id], so no longer inside the [site-1]/[transfer] folder anymore."

It seems the below link is not updated:
https://nvflare.readthedocs.io/en/latest/real_world_fl/workspace.html#client-workspace

FYI.

**Comment by YuanTingHsieh** [comment]
@chanfm81 in the future please try to follow the issue template to raise an issue thanks!

**Comment by YuanTingHsieh** [comment]
This message `2023-02-10 17:02:45,379 - ProcessExecutor - INFO - run (f9b0d6e7-e1ac-4d0a-b99e-7e457a4e12bf): child worker process finished with execution code: -9` is not there anymore after PR https://github.com/NVIDIA/NVFlare/pull/1380
