### ISSUE TITLE
[BUG] unable to handle command: simulator due to: 'run_status', please check syntax 

### ISSUE THREAD

**Issue by pygabc1** [NVIDIA/NVFlare#1371]
The following error occurs sometimes, and sometime the error is gone if I restart my computer. It happened frequently if I run two python (pycharm) scripts in one container. But now 5~6 times consecutively this error are occurring even I am using only ONE python (pycharm) script in a container. Any advice would be appreciated.

> root@~~# cp -rf XAI_Idealist_hello-pt-v4/examples/xai-idealist WorkSpaceIdealist/
> root@~~# nvflare simulator -w WorkSpaceIdealist/workspace -n 2 -t 2 WorkSpaceIdealist/xai-idealist
> unable to handle command: simulator due to: 'run_status', please check syntax 
> usage: nvflare simulator [-h] [-w WORKSPACE] [-n N_CLIENTS] [-c CLIENTS] [-t THREADS] [-gpu GPU] [-m MAX_CLIENTS] job_folder
> 
> positional arguments:
>   job_folder
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -w WORKSPACE, --workspace WORKSPACE
>                         WORKSPACE folder
>   -n N_CLIENTS, --n_clients N_CLIENTS
>                         number of clients
>   -c CLIENTS, --clients CLIENTS
>                         client names list
>   -t THREADS, --threads THREADS
>                         number of parallel running clients
>   -gpu GPU, --gpu GPU   list of GPU Device Ids, comma separated
>   -m MAX_CLIENTS, --max_clients MAX_CLIENTS
>                         max number of clients

**Comment by YuanTingHsieh** [comment]
Hi @pygabc1 thanks for the interest.

Please open a new issue following the bug issue template.
Please also provide your OS, Python version NVFlare version, thank you!
