### ISSUE TITLE
[BUG] NVFlare job does not create best_FL_global_model.pt in v2.2.2+

### ISSUE THREAD

**Issue by ericchu0** [NVIDIA/NVFlare#1389]
**Describe the bug**
_Problem_
In NVFlare 2.2.2+, the `contribution_round` variable in `intime_model_selector.py` is not assigned and takes the value `None`. Thus, `IntimeModelSelector` never triggers the event to save current model as best model, and the `best_FL_global_model.pt` is never created.

The current assignment call in `intime_model_selector.py` is as follows:
`contribution_round = shareable.get_header(AppConstants.CONTRIBUTION_ROUND)`

_Solution_
Not sure if the `contribution_round` info is intended to be in shareable `__headers__`. (I am testing with NVlFlare's `ScatterAndGather`.) When `IntimeModelSelector._before_accept` is triggered, I can only find `contribution_round` in the shareable `__cookie__jar` and not in the general headers. In `ScatterAndGather`, `contribution_round` gets stored in headers during `_accept_train_results`.

The following call resolves the issue for me:
`contribution_round = shareable.get_cookie(AppConstants.CONTRIBUTION_ROUND)`

**To Reproduce**
1. Run an FL job.
2. Check logs or downloaded job to see if best_FL_global_model.pt exists. 

**Expected behavior**
I expect `best_FL_global_model.pt` to be available after issuing download_job from NVFlare console.

**Desktop:**
 - OS: ubuntu 20.04
 - Python Version 3.8.12
 - NVFlare Version 2.2.5

**Comment by YuanTingHsieh** [comment]
Hi @ericchu0 thank you for raising this issue and provide your solution!

The root cause is this PR: https://github.com/NVIDIA/NVFlare/pull/880

I will submit a PR to fix this.

**Comment by YuanTingHsieh** [comment]
Hi @ericchu0 thanks for raising the issue and your solution.

I will submit a PR to fix this.

**Comment by ericchu6** [comment]
@YuanTingHsieh thanks!
