### ISSUE TITLE
[BUG] cannot install nvflare=2.3.0

### ISSUE THREAD

**Issue by pygabc1** [NVIDIA/NVFlare#1721]
Hi, my python version is 3.8.13 (linux OS) and updated pip as recommended in https://github.com/NVIDIA/NVFlare/issues/1240 , but I still have same issue, which is

> python -m pip install nvflare==2.3.0                                                                                                                                                                                ERROR: Could not find a version that satisfies the requirement nvflare==2.3.0 (from versions: none) ERROR: No matching distribution found for nvflare==2.3.0

**Comment by YuanTingHsieh** [comment]
Hi @pygabc1 thanks for the interest and the question!

You might want to follow the issue template next time.

I notice your command you type "python", what if you change to "python3"?


I just tried on my machine and the following command works.

Steps:

```
yuantingh@642a59d-lcedt:~$ python3 -m venv test_venv
yuantingh@642a59d-lcedt:~$ source test_venv/bin/activate
(test_venv) yuantingh@642a59d-lcedt:~$ python3 -V
Python 3.8.10
(test_venv) yuantingh@642a59d-lcedt:~$ python3 -m pip install nvflare==2.3.0
```

If changing to "python3" does not solve your issue, can you share your result of the following commands:

 - `lsb_release -a`
 - `uname -a` 
 - `python -V` 
 - `python3 -V`

**Comment by pygabc1** [comment]
> * uname -a

Hi, Yuan, Thank you for your reply. 

> 
root@fc0b1fd170af:/# python -V
Python 3.8.13
root@fc0b1fd170af:/# python3 -V
Python 3.8.13
root@fc0b1fd170af:/# uname -a
Linux fc0b1fd170af 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 GNU/Linux

**Comment by pygabc1** [comment]
I realized I forgot to use my corporate proxy server. Thank you.
