### ISSUE TITLE
[BUG] Flask vulnerable

### ISSUE THREAD

**Issue by mingxin-zheng** [NVIDIA/NVFlare#1744]
**Describe the bug**

Hello!

Two weeks ago, there was a report of this vueneratiblity related to the flask: 
https://github.com/advisories/GHSA-m2qf-hxjv-5gpq

Would nvflare consider using the patched version (2.2.5/2.3.2)? Thanks!

**Comment by YuanTingHsieh** [comment]
I think we mainly use Flask for dashboard.
@IsaacYangSLA and @nvkevlu can you confirm and see what we can do about this? thanks

**Comment by mingxin-zheng** [comment]
Thanks @chesterxgchen  and @YuanTingHsieh .

**Comment by YuanTingHsieh** [comment]
Solved by #1817
