### ISSUE TITLE
[BUG] "unable to handle command: simulator due to: 'run_status', please check syntax"

### ISSUE THREAD

**Issue by Nicholas-B1** [NVIDIA/NVFlare#1843]
**Describe the bug**
When running the cifar10 simulation running the ./run_simulator.sh cifar10_fedavg 1.0 8 8 or any other simulator command I get the error "unable to handle command: simulator due to: 'run_status', please check syntax"

**To Reproduce**
Followed steps on READme on GitHub until the error came up.

**Expected behavior**
To run the simulated FL example and show output shown from GitHub

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Python Version 3.10.6
 - NVFlare Version 2.3.1

**Comment by YuanTingHsieh** [comment]
@yhwen I think we have a problem in https://github.com/NVIDIA/NVFlare/blob/dev/nvflare/private/fed/app/simulator/simulator_runner.py#L332-L353

If mpm.run raise Exception before it sets `return_dict`
Then this situation as described will happen.

But I don't know why mpm.run raise Exception before it sets `return_dict`,

Note that we have similar issue raised in https://github.com/NVIDIA/NVFlare/discussions/1373

**Comment by YuanTingHsieh** [comment]
@Nicholas-B1 thanks for reporting the issue.

I've tried locally and it works fine for me.

Can you attach a screenshot?
Are there some other texts print out?

**Comment by Nicholas-B1** [comment]
Below the error about syntax it gives me the proper syntax for the function nvflare simulate however I am just running the simulation from the .sh file so I do not know why that function wouldn’t be working correctly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yhwen** [comment]
@Nicholas-B1 This could be caused by the machine resources you were trying to run this simulator job. When you run the command "./run_simulator.sh cifar10_fedavg 1.0 8 8", the first 8 is the number of threads to run the simulator. Which means there will be 8 threads to run the client jobs at the same time. The second 8 is the number of clients. I suspect that your machine does not have enough resources (CPU, memory, etc) to run 8 threads at the same time. Can you try lower this number and run it again? For example:

./run_simulator.sh cifar10_fedavg 1.0 4 8        //  Use 4 threads to simulate 8 clients run, client jobs will take turn to run

./run_simulator.sh cifar10_fedavg 1.0 2 8        // Further reduce the number of threads to simulate the clients run

Or even reduce the number of clients to run this experiment:

./run_simulator.sh cifar10_fedavg 1.0 1 4        // Use single thread to simulate 4 clients run, all the clients will be run one by one in turn

**Comment by Nicholas-B1** [comment]
The same issue occurs when I do the central simulation example the first one shown on the GitHub which uses a lot less resources.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yhwen** [comment]
Could you please zip and upload the "simulator_job" folder in the simulator workspace, which contains the server log and clients run logs, so we can investigate the issues you had with your experiment?

**Comment by YuanTingHsieh** [comment]
@Nicholas-B1 As @yhwen suggested,

Could you please zip and upload the "simulator_job" folder in the simulator workspace, which contains the server log and clients run logs, so we can investigate the issues you had with your experiment?

You can send it to my email: yuantingh@nvidia.com

Thanks

**Comment by YuanTingHsieh** [comment]
@Nicholas-B1 can you try if this: https://nvflare.readthedocs.io/en/main/getting_started.html#quick-start-with-simulator
works for you on your end?

**Comment by plaipmc** [comment]
I have the same problem with you but I found something what work for me.

After using set_env.sh file, I update, clone the example first and then install nvflare. Like this.

sudo apt update
git clone https://github.com/NVIDIA/NVFlare.git
pip install nvflare

**Comment by Nicholas-B1** [comment]
Where is the set_env.sh file? And do you clone the example after you have made your virtual enviroment?
________________________________

**Comment by plaipmc** [comment]
Here is the set_env.sh file. I use it after I follow the examples.

https://github.com/NVIDIA/NVFlare/blob/main/examples/set_env.sh

And I update first and clone it after I made the virtual environment.

**Comment by Nicholas-B1** [comment]
Is the link you provided the updated GitHub branch to work with the examples? I might have cloned onto my machine the older version.
________________________________

**Comment by YuanTingHsieh** [comment]
@plaipmc thanks for sharing your solutions.
Looks like it is an environment setup issue.

@Nicholas-B1 Please follow the summarize suggest sequence of actions:

## install NVFlare 2.3.1
```
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install nvflare==2.3.1
```

## setup NVFlare repo and set to 2.3 so examples are good
```
git clone https://github.com/NVIDIA/NVFlare.git
cd NVFlare
git checkout 2.3
```

## setup example specifics
```
cd examples/advanced/cifar10/cifar10-sim/
pip install -r ./requirements.txt
export PYTHONPATH=${PWD}/..
./prepare_data.sh
```

**Comment by Nicholas-B1** [comment]
I still get the same issue when trying to run this line in the virtual environment. I got this line from the GitHub is the syntax wrong with this line when it come to the NVFlare simulator command?

[cid:6f2b3fa5-123f-46d0-8c93-771377661310]
________________________________

**Comment by YuanTingHsieh** [comment]
@Nicholas-B1 

Can you try this simple example instead?

`nvflare simulator -w /tmp/nvflare/hello-numpy-sag -n 2 -t 2 examples/hello-world/hello-numpy-sag/jobs/hello-numpy-sag`

**Comment by Nicholas-B1** [comment]
It is still having issues with that example. I was able to get the base example in the documentation the hello-pt
[cid:cfda0525-0a4a-4f70-8c25-e296295e880a]
________________________________

**Comment by Nicholas-B1** [comment]
I will keep trying to see if I can get it to work.
________________________________

**Comment by Nicholas-B1** [comment]
How do I get out of the dev branch? Moving to 2.3.1 takes me to dev automatically.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by plaipmc** [comment]
> @plaipmc thanks for sharing your solutions. Looks like it is an environment setup issue.
> 
> @Nicholas-B1 Please follow the summarize suggest sequence of actions:
> 
> ## install NVFlare 2.3.1
> ```
> python3 -m venv venv
> source venv/bin/activate
> pip install --upgrade pip
> pip install nvflare==2.3.1
> ```
> 
> ## setup NVFlare repo and set to 2.3 so examples are good
> ```
> git clone https://github.com/NVIDIA/NVFlare.git
> cd NVFlare
> git checkout 2.3
> ```
> 
> ## setup example specifics
> ```
> cd examples/advanced/cifar10/cifar10-sim/
> pip install -r ./requirements.txt
> export PYTHONPATH=${PWD}/..
> ./prepare_data.sh
> ```

I follow this step already. Before setup example specifics, I try the simulator with hello-numpy-cross-val jobs and It worked. But after I setup example specifics, the bug come back again.

**Comment by plaipmc** [comment]
I mean after I run this command.

cd examples/advanced/cifar10/cifar10-sim/
pip install -r ./requirements.txt
export PYTHONPATH=${PWD}/..
./prepare_data.sh

**Comment by plaipmc** [comment]
`nvflare --version`

> NVFlare version is 2.3.1

`git branch`

> \* 2.3 dev

The command I use:

`./run_simulator.sh cifar10_central 0.0 1 1`

Error:

> ServerCommandAgent - INFO - ServerCommandAgent cell register_request_cb: server.simulate_job
unable to handle command: simulator due to: 'run_status', please check syntax

**Comment by YuanTingHsieh** [comment]
@plaipmc thanks for the report!

Can you start over again in a new terminal, BUT this time before you do "setup example specifics" steps
You run `echo $PYTHONPATH` and `uname -a`

And use the following setup example specifics steps:

```
cd examples/advanced/cifar10/cifar10-sim/
pip install -r ./requirements.txt
export PYTHONPATH=${PYTHONPATH:+${PYTHONPATH}:}${PWD}/..
./prepare_data.sh
```

**Comment by plaipmc** [comment]
What the value of $PYTHONPATH whould be?

**Comment by plaipmc** [comment]
I try it already. I create the new virtual environment and redo all the step and 
`echo $PYTHONPATH` - not thing happen and 
`uname -a` 

> Linux NVFlareCifar10 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

After use the following setup example specifics steps:
`echo $PYTHONPATH` 

> <myfolderpath>/NVFlare/examples/advanced/cifar10/cifar10-sim/..

But still the same.

**Comment by annabeer** [comment]
I am leveraging a Apple M2 Pro chip and for me this issue was resolved for the by removing the install of tensorflow.

**Comment by YuanTingHsieh** [comment]
> I am leveraging a Apple M2 Pro chip and for me this issue was resolved for the by removing the install of tensorflow in the requirements.txt file.

Thanks for sharing your solution, this is very interesting.

**Comment by YuanTingHsieh** [comment]
@plaipmc @Nicholas-B1 can you try "removing the install of tensorflow in the requirements.txt file."?

**Comment by plaipmc** [comment]
I remove the tensorflow in requirements.txt file and it works!! Thank you @annabeer @YuanTingHsieh . No error anymore.

**Comment by YuanTingHsieh** [comment]
@plaipmc Inside the virtual environment, you need to go to the directory where you put the cifar10 examples:

`cd [where you clone NVFlare repo]/examples/advanced/cifar10/cifar10-sim`

And then run the following:

`export PYTHONPATH=${PYTHONPATH:+${PYTHONPATH}:}${PWD}/..`

**Comment by plaipmc** [comment]
Oh I might forgot this line. Thank you so much!!

**Comment by Nicholas-B1** [comment]
I removed tensorflow from the requirements. After doing all the setup I run v
________________________________

**Comment by Nicholas-B1** [comment]
After doing these steps and removing tensorflow running (./run_simulator.sh cifar10_central 0.0 1 1) gets stuck while running.

**Comment by Nicholas-B1** [comment]
[log.txt](https://github.com/NVIDIA/NVFlare/files/12088546/log.txt)
 Here is the log after I had to force quit because it was getting stuck at the beginning.

**Comment by holgerroth** [comment]
Is this a gpu or cpu environment?

**Comment by Nicholas-B1** [comment]
I am running this on an Ubuntu Virtual Machine so I would assume cpu.

**Comment by Nicholas-B1** [comment]
Hello pt worked for me when I went through the first example on the NVFlare documentation. I am unsure what I could be doing wrong I think I am going through all the steps correctly.

**Comment by Nicholas-B1** [comment]
![image](https://github.com/NVIDIA/NVFlare/assets/98412792/530c479e-3715-4e2d-858c-40124b877690)
This is where I get stuck in the simulator command

**Comment by holgerroth** [comment]
Oh. This is different from the output log.txt you shared previously. I think the client is already performing the training, which can be pretty slow, depending on your hardware. It seems you only use CPU. Hence, the training speed is slow. So, the client might not be stuck but is just training. 

If you want to make sure the training continues, you can put another `self.log_info` to print each iteration of the training loop [here](https://github.com/NVIDIA/NVFlare/blob/147278078f235ea19878ed0a0ef7413f23c84aef/examples/advanced/cifar10/pt/learners/cifar10_learner.py#L216).

**Comment by Nicholas-B1** [comment]
When it completes I do not see anything in the cross site val. Where are the results stored or does this happen when it does not run correctly?

**Comment by holgerroth** [comment]
Please share logs and the output folder (at least tree command of the structure). Then we can investigate what is going on.

**Comment by Nicholas-B1** [comment]
It seems to be working now! Just really slow is there a way to speed up the simulation?

**Comment by YuanTingHsieh** [comment]
@Nicholas-B1 you can utilize a GPU to speed up your training progress.

Other than that, maybe data loading pin_memory and using multiple workers there will help.
Please open another discussion for "speed up", I will submit a PR to make TF optional to fix this issue.
