### ISSUE TITLE
Details and Pre-processing steps for Retina Dataset

### ISSUE THREAD

**Issue by siomvas** [NVIDIA/NVFlare#1846]
Hello,

Is there any chance you can share more details or code for the pre-processing used to end up with the Retina dataset used in the FedSM and FedCE papers? For example:

- What is the total number of samples?
- Are you using both Glaucoma and normal images?
- RIGA: How are the different annotators combined?
- Are 

And if you could share any of the code used to end up with niftii labels that'd be amazing since the datasets all have different formats.

Many thanks in advance!

**Comment by YuanTingHsieh** [comment]
@holgerroth and @ZiyueXu77 can you help comment on this, thanks!

**Comment by ZiyueXu77** [comment]
Hi @siomvas, we randomly split the dataset (including everything healthy/diseased) to train/val/test 0.5/0.25/0.25 (separately for each category - normal, etc.). 
For images with many annotations, we created a gray-scale map (0-255) by adding up all annotations, then perform a thresholding at 100 - theoretically, it is equivalent to majority voting (slightly biased towards "more inclusive"). 
Unfortunately we are not approved to use some of these datasets by illustrating their applications using NVFlare, so we cannot share our preprocessing code on them, data preprocessing indeed takes some time. Let me know if you have further questions.
