### ISSUE TITLE
[BUG] "ERROR: Could not find a version that satisfies the requirement openmined.psi==1.1.1 (from versions: 0.3.2, 0.3.4, 0.3.5)"

### ISSUE THREAD

**Issue by annabeer** [NVIDIA/NVFlare#1857]
**Describe the bug**
Running the vertical federated learning example on an Apple M2 Pro Chip does not work. The issue is that "openmined.psi==1.1.1" cannot be loaded. When removing the version 1.1.1 it encounters future issues so there is an underlying issue with M2 Chip. If I run the same example on a "Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz"  this issue is not encountered and it runs perfectly. 

**To Reproduce**
Steps to reproduce the behavior please leverage a M2 Chip. 
1. Go to 'examples/advanced/vertical_federated_learning/cifar10-splitnn'
2. Run 'requirements.txt'

**Expected behavior**
To work on an M2 Chip as possible from an "Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz"

**Comment by YuanTingHsieh** [comment]
@annabeer thanks for raising the issue!

So the problem really is with openmined.psi library.

Can you open an issue at their repo: https://github.com/OpenMined/PSI/issues ?


Meanwhile we could check if we can find alternatives for this library for M2 chip.
@holgerroth do you know any?

**Comment by holgerroth** [comment]
Yes, I would file an issue in OpenMined's repo. An alternative implementation could be of PSI could be this one https://github.com/Visa-Research/volepsi.

**Comment by holgerroth** [comment]
@chesterxgchen, @IsaacYangSLA might be able to comment on this one.

**Comment by YuanTingHsieh** [comment]
Closed as this is not NVFlare issue.
Should keep tracking in the OpenMined's repo.
And as @holgerroth suggested, alternative implementation of PSI could be tried: https://github.com/Visa-Research/volepsi.
