### ISSUE TITLE
Real-world example with provisioning

### ISSUE THREAD

**Issue by wanderine** [NVIDIA/NVFlare#1898]
I'm missing an a real-world example of NVFlare where you first do the provisioning and then run the federation on for example 3 clients (i.e. 3 different computers) and a server (computer 4), instead of running everything on the same computer.

**Comment by YuanTingHsieh** [comment]
Please check https://nvflare.readthedocs.io/en/stable/real_world_fl.html
and https://github.com/NVIDIA/NVFlare/tree/dev/examples/advanced/cifar10/cifar10-real-world

In brief:
1. After provision, NVFlare will generate one folder for each "site" you specify in the "project.yml".
2. You need to put those folders into each site and launch the NVFlare server/client.
3. Submit a job using "admin client command line interface"

Please let us know if you run into any problem following the materials!

**Comment by wanderine** [comment]
Where in the project.yml file do I specify the address of the server? It is not clear to me.

https://github.com/NVIDIA/NVFlare/blob/dev/examples/advanced/cifar10/cifar10-real-world/workspaces/secure_project.yml

**Comment by YuanTingHsieh** [comment]
This line: https://github.com/NVIDIA/NVFlare/blob/dev/examples/advanced/cifar10/cifar10-real-world/workspaces/secure_project.yml#L12

Right now in this example we are using "localhost" which after DNS resolution will translate to 127.0.0.1.
Let's say you have something running on AWS, then you change this name the FQDN of your AWS server.
You can found that by reading their documentation: https://docs.aws.amazon.com/managedservices/latest/userguide/find-FQDN.html

**Comment by YuanTingHsieh** [comment]
@wanderine yes, you can remove the overseer section in project.yml:

```
  - name: overseer.example.com
    type: overseer
    org: nvidia
    protocol: https
    api_root: /api/v1
    port: 8443
```

**Comment by wanderine** [comment]
It seems that using the same name (address) for the overseer as server is not allowed? Why is that? So I need another computer for overseer?

**Comment by holgerroth** [comment]
The example [project](https://github.com/NVIDIA/NVFlare/blob/db06578cd269091cecbbc3cf8f52a0b3b3174659/examples/advanced/cifar10/cifar10-real-world/workspaces/secure_project.yml#L56) uses a dummy overseer. So it shouldn't matter what address you put there. The overseer is there to manage high-availability in production deployment - so it should be running on a different machine than the server. See [here](https://nvflare.readthedocs.io/en/main/programming_guide/high_availability.html) for details. CC @nvidianz, @IsaacYangSLA

**Comment by YuanTingHsieh** [comment]
@wanderine as @holgerroth explained, you can just use DummyOverseerAgent as in this file: [https://github.com/NVIDIA/NVFlare/blob/main/examples/advanced/cifar10/cifar10-real-world/workspaces/secure_project.yml#L56](https://github.com/NVIDIA/NVFlare/blob/main/examples/advanced/cifar10/cifar10-real-world/workspaces/secure_project.yml#L56)

Please re-open this issue if you have more questions
