### ISSUE TITLE
Clients don't shut down

### ISSUE THREAD

**Issue by holgerroth** [NVIDIA/NVFlare#193]
Using admin API with

```
    runner.run(run_number, args.app, restart_all_first=False, shutdown_on_error=True, shutdown_at_end=True,
               timeout=7200, min_clients=args.min_clients)
```
clients don't shut down after end of run.

Similarly when using the admin client console.

Issue was probably introduced with this change https://github.com/NVIDIA/NVFlare/pull/174/files#diff-08f576a2965a40b523edfef473ea838f2a28c0bbce28a1c0bf7015e42dade1c8L345

**Comment by YuanTingHsieh** [comment]
By @yhwen : The root cause of this shutdown issue is the wrong order in the _shutdown_app_on_clients() in the server/training_cmds.py.
