### ISSUE TITLE
[BUG]ERROR - Simulator setup error: RuntimeError: ValueError: App hello-pt in deploy_map doesn't exist for job hello-pt

### ISSUE THREAD

**Issue by yizhihenpidehou** [NVIDIA/NVFlare#1943]
**Describe the bug**
When I try to follow the example in [Running an example application](https://nvflare.readthedocs.io/en/main/getting_started.html) with the FL Simulator. I got an error message in my terminal. 
ERROR - Simulator setup error: RuntimeError: ValueError: App hello-pt in deploy_map doesn't exist for job hello-pt

**To Reproduce**
1. git clone https://github.com/NVIDIA/NVFlare.git
2. mkdir simulator-example
cp -rf NVFlare/examples/hello-world/hello-pt simulator-example/
However, I notice there may have some outdated command since I see:
cp -rf NVFlare/examples/hello-pt simulator-example/
in [Running an example application](https://nvflare.readthedocs.io/en/main/getting_started.html).
3. Install requirements in my conda environment.
4. Run commands :
mkdir simulator-example/workspace
nvflare simulator -w simulator-example/workspace -n 2 -t 2 simulator-example/hello-pt

5. See error:
ERROR - Simulator setup error: RuntimeError: ValueError: App hello-pt in deploy_map doesn't exist for job hello-pt

**Expected behavior**
Running successfully, and see logs of the output, site and global models, cross-site validation results

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Linux-5.4.0-150-generic-x86_64-with-glibc2.17
 - Python Version 3.8.15
 - NVFlare Version 2.3.2

**Additional context**
none

**Comment by SYangster** [comment]
Hi, you are right the command in the [Running an example application](https://nvflare.readthedocs.io/en/main/getting_started.html#running-an-example-application) is outdated: 
`nvflare simulator -w simulator-example/workspace -n 2 -t 2 simulator-example/hello-pt`

If you take a look at the folder structure, inside `simulator-example/hello-pt` is `jobs/hello-pt`, which is the job we want to use when running the simulator. Therefore the correct command would be: 
`nvflare simulator -w simulator-example/workspace -n 2 -t 2 simulator-example/hello-pt/jobs/hello-pt`

Thanks for letting us know, we will update the docs.

**Comment by yizhihenpidehou** [comment]
Thank you! Btw, I have another question, when I run the FedXGBoost example, the AUC metric did not be recorded into the client's log, but only print in the terminal, how can I set it to write the data into the log? :)

**Comment by SYangster** [comment]
The reason it’s not saved into the logs is because the metrics are printed via the [xgboost train](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.train) `verbose_eval` parameter rather than through the logger. If you would like to log the results, you can modify the code to save `eval_result` for [eval metrics](https://xgboost.readthedocs.io/en/stable/python/examples/evals_result.html) and log using `self.log_info()` or write to a file etc. Also if you would like to save auc metrics to tensorboard events you can optionally install and use tensorboard/torch.

**Comment by yizhihenpidehou** [comment]
Thanks you very much!! I have successfully gotten the result!!
