### ISSUE TITLE
[BUG] xgboost : 'ModelLearnable' but received <class 'NoneType'>

### ISSUE THREAD

**Issue by pygabc1** [NVIDIA/NVFlare#1974]
When I run 
`bash run_experiment_simulator.sh`
for xgboost/tree-based,
I have the error of

> Aborting current RUN due to FATAL_SYSTEM_ERROR received: Expected global weights to be of type `ModelLearnable` but received <class 'NoneType'>

It is linux OS and 3.8 python, and 2.2 NVFlare version.

**Comment by YuanTingHsieh** [comment]
@pygabc1 

I just tried on my machine and it works fine.
Please make sure you are using the examples from the **correct branch**: https://github.com/NVIDIA/NVFlare/tree/2.2.5/examples/xgboost

You can do git checkout 2.2.5 to get the correct examples.

My environment:

Ubuntu 20.04
Python 3.8.10
NVFlare 2.2.5

**Comment by pygabc1** [comment]
The path for dataset of higgs.csv is correct, isn't it?
![image](https://github.com/NVIDIA/NVFlare/assets/31337772/f0d8fb1e-8a3e-40b7-8e95-e3751b12a74d)

**Comment by pygabc1** [comment]
Thank you so much for your help.

> root@fc0b1fd170af:/Feb23/idealist/idealist/NVFlare-2.2_xgboost/NVFlare-2.2/examples/xgboost# python3 -V
Python 3.8.13
root@fc0b1fd170af:/Feb23/idealist/idealist/NVFlare-2.2_xgboost/NVFlare-2.2/examples/xgboost# python3 -m pip list | grep "nvflare"
nvflare                  2.3.0
root@fc0b1fd170af:/Feb23/idealist/idealist/NVFlare-2.2_xgboost/NVFlare-2.2/examples/xgboost# python3 -m pip list | grep "xgboost"
xgboost                  1.7.5
root@fc0b1fd170af:/Feb23/idealist/idealist/NVFlare-2.2_xgboost/NVFlare-2.2/examples/xgboost# git branch
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by YuanTingHsieh** [comment]
@pygabc1 from what you shared, your nvflare version is actually 2.3.0 so that will NOT work with 2.2 example.

If you want you can instead use the examples in NVFlare 2.3 branch

**Comment by pygabc1** [comment]
@YuanTingHsieh Thank you so much.
