### ISSUE TITLE
Revisit MetaKey in dxo.py

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#219]
Do we really need MetaKey in nvflare/apis/dxo.py?

Since they are used only in app_common, should they just be AppConstants?

**Comment by chesterxgchen** [comment]
@YuanTingHsieh  @yhwen @IsaacYangSLA to discuss

**Comment by YuanTingHsieh** [comment]
since they are specific to each DXO's meta, we keep them there.
