### ISSUE TITLE
 client runner keeps restarting and closing the connection until my model is saved in the mlflow instance

### ISSUE THREAD

**Issue by falibabaei** [NVIDIA/NVFlare#2326]
I use Nvflare version 2.4.0rc6+11.gfdcf5785.dirty and a client api to convert my custom code to the Nvflare version. My code uses Tensorflow 2.10 and I use `model_persistor.TFModelPersistor` as the model persistor. I have changed the model persistor save_model so that it saves the global_model on my mlflow instance. as follows
```python
    def save_model_file(self, save_path: str, result, run_ids):
        """Saves model.

        Args:
            model_learnable: ModelLearnable object
            fl_ctx: FLContext
        """
        # result = unflat_layer_weights_dict(model_learnable[ModelLearnableKey.WEIGHTS])
        for k in result:
            layer = self.model.get_layer(name=k)
            layer.set_weights(result[k])
        self.model.save_weights(save_path)

        input_arr = tf.random.uniform((1, SIZE_H, SIZE_W, 3))

 
        custom_objects = {
            "Addons>SigmoidFocalCrossEntropy": tfa.losses.SigmoidFocalCrossEntropy(
                alpha=alpha, gamma=gamma
            ),
        }
        for metric_name, metric_instance in config["eval"][
            "SM_METRICS"
        ].items():
            custom_objects[metric_name] = eval(metric_instance)
        custom_objects["f1-score"] = sm.metrics.FScore()
        server_key = next(
            (
                key
                for key in run_ids.keys()
                if key.startswith("server")
            ),
            None,
        )
        run_id = run_ids[server_key]
        print("run_id of the server: %s" % run_id)

        with mlflow.start_run(run_id=run_id):
            _ = self.model(input_arr)
            mlflow.keras.log_model(
                self.model,
                custom_objects=custom_objects,
                artifact_path="tf-models",
            )
```
Since I use unet, it takes some time to save the model in the mlflow instance. But during this time, the client runner keeps restarting and closing the connection until my model is saved in my mlflow instance. How can I prevent this restarting and closing of the connection until my model is saved? In the attachment, you can see my log 
[log.txt](https://github.com/NVIDIA/NVFlare/files/14087509/log.txt)

**Comment by YuanTingHsieh** [comment]
@falibabaei  thanks for the report!

Can you provide more information?
Your job's config_fed_server / config_fed_client / and meta.json / custom client code ... etc.

Thanks!

**Comment by falibabaei** [comment]
Hi,
Thank you for your reply. I use the flag launch_once=true in my config_fed_client.conf, but I still have that issue. I am in the first step of converting my code using decorators to the nvflare version and for debug purposes I am using the nvflare simulator to run the code. Unfortunately, since the custom code is not in the public repository, I cannot share the repository, but my train function is
```python 
   @flare.train
    def train(input_model=None):
        """
        Train UNet model with training images (X_train) and masks (y_train)
        and user-defined parameters.
        Use test dataset only to visualise performance before final evaluation.
        X data can be 3 channel or of different dimension (UNet will automatically be adapted).

        :param X_train: train images
        :param y_train_onehot: corresponding onehot encoded train masks
        :param X_test: test images
        :param y_test_onehot: corresponding onehot encoded test masks
        :param model_path: (Path) path to which model will be saved
        :return: model saved to provided path
        """
        start = time.time()
        # Check that provided path can be used for saving model
        assert (
            type(model_path) == PosixPath
            and model_path.suffix == ".h5py"
        ), f"Provided model path '{model_path}' is not a Path ending in '.h5py'!"

        # (5) loads model from NVFlare
        for k, v in input_model.params.items():
            model.get_layer(k).set_weights(v)
        cfg["epochs"] = 1
        _logger.info("Training model...")
        history = model.fit(
            X_train,
            y_train_onehot,
            batch_size=cfg["batch_size"],
            verbose=2,
            epochs=cfg["epochs"],
            validation_data=(X_test, y_test_onehot),
            callbacks=[CustomEpochLogger()],
        )

        # print('history is ', history.history)
        metrics = {
            metric: values[-1]
            for metric, values in history.history.items()
        }

        mlflow_writer.log_metrics(
            metrics=metrics, step=input_model.current_round
        )
        duration = time.time() - start
        _logger.info(
            f"Elapsed time during model training:\t{round(duration / 60, 2)} min"
        )

        # Save trained Model
        # model.save_weights(model_path)
        model.save(model_dir)
        _logger.info(f"Model saved to '{model_path}'.")
        save_model_info(model=model, model_dir=model_dir)

        # save json config to model directory
        # cp_conf(model_dir)
        _logger.info(
            f"Saved configuration of training run to {model_dir}"
        )

        # (3) send back the model to nvflare server
        output_model = flare.FLModel(
            params={
                layer.name: layer.get_weights()
                for layer in model.layers
            },
            metrics=history.history,
        )

        return output_model
``` 
and my configuration for the client and server is attached.
[config_fed_client.txt](https://github.com/NVIDIA/NVFlare/files/14094744/config_fed_client.txt)
[config_fed_server.txt](https://github.com/NVIDIA/NVFlare/files/14094746/config_fed_server.txt)

**Comment by falibabaei** [comment]
@ [chesterxgchen](https://github.com/chesterxgchen) I noticed that even with the flag launch_once= ture, if I use the simulator with the flag -t 1, the process restarts every round.

**Comment by falibabaei** [comment]
@chesterxgchen  I did what you asked but I do not know why I got this message after the first run
  File "custom/train_UNet.py", line 436, in main
    print(f"Currently in round {current_round} out of a total of {total_rounds} rounds")
ValueError: I/O operation on closed file.

[log.txt](https://github.com/NVIDIA/NVFlare/files/14110996/log.txt)

**Comment by falibabaei** [comment]
@chesterxgchen Thank you. I have added you and  @YuanTingHsieh to the repository. There are some data in the [dataset](https://github.com/falibabaei/murnong_sem-segm-nvflare/tree/main/dataset) to test the code.

**Comment by YuanTingHsieh** [comment]
When sending heartbeats in PipeHandler (Line 323), we use timeout = None, which will be translated to use the default_request_timeout set to 5 seconds. This causes a problem where this send_to_peer(msg) can block the entire _try_read thread for up to 5 seconds. It is supposed to be a fast-checking loop.

When the loop is blocked, it also slows down the follow-up checking/sending heartbeat logic, making the system more prone to timeouts.

I've submitted a PR #2355  to fix it.
