### ISSUE TITLE
Control the frequency of logging

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#238]
Quote @ZiyueXu77 : "Shall we provide some control on the frequent logging printouts?"
For example:

```

FederatedServer - INFO - Fetch task requested from client: client_covid (067cf2b5-20dc-449a-9067-9ea9ec3d6081)
ServerRunner - INFO - [run=1, wf=scatter_and_gather, peer=client_covid, peer_run=1]: got task request from client
ServerRunner - INFO - [run=1, wf=scatter_and_gather, peer=client_covid, peer_run=1]: no task currently for client - asked client to try
again later

```

**Comment by YuanTingHsieh** [comment]
A related topic:

If we enable the TB streaming on the client side, we will see a lot of the following logging information:

```
FederatedClient - INFO - Starting to send aux messagee.
Communicator - INFO - Send AuxMessage to XXX server
```

I think we want to change these AuxMessage related logging level to DEBUG, what do you think?

**Comment by yanchengnv** [comment]
Yes, agreed. We probably should make many of these log messages into DEBUG level.

Yuan-Ting, please take a look at this kind of messages. In addition to the aux and fed client communicator, also look at ClientRuner, ServerRunner and Controller impl.

**Comment by ZiyueXu77** [comment]
Agreed, DEBUG level will be a good fit

**Comment by YuanTingHsieh** [comment]
Sure, let me take a look at these and prepare a PR so we can review it.
