### ISSUE TITLE
Startup folder not configured correctly

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#239]
I think the `app_root="startup"` should be `app_root=startup` [here](https://github.com/NVIDIA/NVFlare/blob/fa20e5e27b01e0f66cbefea229aed2cf6729663d/nvflare/private/fed/app/server/server_train.py#L67-L69)

If you like I can submit a PR?

**Comment by YuanTingHsieh** [comment]
Thanks for the issue.

I think you are right, can you submit a PR to change this?
