### ISSUE TITLE
Missing classification results for the FL linear regression tutorial

### ISSUE THREAD

**Issue by kandalto** [NVIDIA/NVFlare#2398]
Hi,

I'm following the tutorial at NVFlare/examples/hello-world/step-by-step/higgs/sklearn-linear/sklearn_linear.ipynb. In the "Run job in simulator" section it says that after running the 
```!nvflare simulator /tmp/nvflare/jobs/sklearn_sgd -w /tmp/nvflare/sklearn_sgd -n 3 -t 3``` 
command FL training log should contain the following entry:  
```site-1 reports site-1: local model AUC: 0.6351``` 
However, in the entire 2881 lines of the federated log, there is no mention of AUC  whatsoever. Is the ipynb file outdated or am I encountering some bug? The rest of the ipynb produces the expected results.

Thanks!

**Desktop:**
 - ubuntu 22.04.4
 - Python Version 3.10.13
 - NVFlare Version 2.4

**Comment by YuanTingHsieh** [comment]
@ZiyueXu77 can you check this when you got time? thanks

**Comment by ZiyueXu77** [comment]
@YuanTingHsieh I just ran the tutorial myself but can no longer see the log either, is it related to our updates on log recording (log from local scripts v.s. from flare)?

**Comment by YuanTingHsieh** [comment]
@kandalto thanks for reporting, this is because the external process's output is buffered.
I will submit a PR to change it to be launched un-buffered.
