### ISSUE TITLE
Stateless server

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#242]
Currently if the server goes down during the train then the entire run is invalidated as when the server comes back up it doesn't maintain the state from when it went down.

This is not ideal and could result in wasted computations. The server should store it's state in a persistent data store in order to be able to resume where it left off

**Comment by YuanTingHsieh** [comment]
Thanks for this issue!

Yes, we are aware of this situation.
In our next release (2.1), we will have a way to persistent and restore the server state.

**Comment by chesterxgchen** [comment]
This will addressed in release 2.1
