### ISSUE TITLE
Logic error in InTimeAccumulateWeightedAggregator for multiple DXO

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#248]
If  `aggregation_weights={"dxo1": {"client_0": 1.0, "client_1": 2.0}}`

and `expected_data_kind={"dxo1": DataKind.WEIGHT_DIFF, "dxo2": DataKind.WEIGHT_DIFF}`

https://github.com/NVIDIA/NVFlare/blob/main/nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py#L85

Will set `aggregation_weights_dict["dxo2"]` to `{"dxo1": {"client_0": 1.0, "client_1": 2.0}}`

Which is not correct.

**Comment by YuanTingHsieh** [comment]
Hi @holgerroth ,

This is a logic error.
But what do you think might be a good solution:

1. We require users to specify the "complete" aggregation weight:
    means user need to specify both "dxo1" and "dxo2" in the aggregation weight,
    otherwise we raise an error

2. We still allow the weight to be like this way.
    For the "dxo2", we just take the "dxo1"'s aggregation weight.
 
3. We still allow the weight to be like this way. 
    For the "dxo2", we just set its aggregation weight to be `{}`.

**Comment by holgerroth** [comment]
I would say, we just apply clien1's aggregation weight to all dxo's in client1's collection, and so on for other clients.

**Comment by YuanTingHsieh** [comment]
The conclusion is:

1. If the aggregation_weights is provided as `{"client1": 1, "client2": 2}`, then it will be applied to all DXOs in the dxo collection
2. If the aggregation_weights is provided in a dict of dict format like `{"dxo1": {"client1": 1, "client2": 2}}`, then we will check all the dxo in expected_data_kind need to exist in this aggregation weights, otherwise we raise an exception.

I will modify the PR as requested.
