### ISSUE TITLE
start_app freezes and no response from clients

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#249]
Hi,

I am trying to build a prod environment using nvflare. In my setup I have one server and two clients, each node is in its own private subnet and the subnets do not route between each other.

The server is fronted by a load balancer that is accessible on `server.nvflare`, the load balancer is accessible from all subnets.

The client's connect to the server successfully, this is confirmed with `check_status server`, shown below
```
> check_status server
FL_app name: ?
Engine status: stopped
Run number has not been set.
Registered clients: 2 
---------------------------------------------------------------------------------------------------------------------
| CLIENT                                          | TOKEN                                | LAST CONNECT TIME        |
---------------------------------------------------------------------------------------------------------------------
| ip-10-0-228-180.ap-southeast-2.compute.internal | 63d874c3-60ee-4724-bb12-603c21970228 | Wed Mar  2 03:27:41 2022 |
| ip-10-0-159-124.ap-southeast-2.compute.internal | 4f047739-efe7-49a6-b9b7-5224e7720aa4 | Wed Mar  2 03:27:44 2022 |
---------------------------------------------------------------------------------------------------------------------
Done [47820 usecs] 2022-03-02 03:28:30.386956
```

Next I follow the steps to upload, deploy
```
> upload_app sepsis
Created folder /workspace/transfer/sepsis
> deploy_app sepsis all
deployed app "sepsis" to Server
--------------------------------------------------------------
| CLIENT                                          | RESPONSE |
--------------------------------------------------------------
| ip-10-0-228-180.ap-southeast-2.compute.internal | OK       |
| ip-10-0-159-124.ap-southeast-2.compute.internal | OK       |
--------------------------------------------------------------
Done [10965147 usecs] 2022-03-02 03:33:09.277277
```
finally when trying to `start_app` the admin client hangs for a while and eventually fails

```
> start_app all sepsis
Error: Could not start the server app.
Done [300122351 usecs] 2022-03-02 03:38:26.784686
> 
```

I then try to restart the clients by issuing the command `restart` in the admin API, shown below

```
> restart client
Enter password to confirm: 
no responses from clients
Done [157381 usecs] 2022-03-02 03:11:20.718412
```

As you can see the response comes back `no responses from clients`. 

I have this setup working locally in a `docker-compose` environment, I am fairly certain the environments apart from the fact that the compose environment all nodes can talk to each other but in the prod environment only the server is accessible.

Any ideas what might be going on here?

Thanks!

**Comment by YuanTingHsieh** [comment]
Hi, 

Thanks for the issue.
Can you please try to deploy and run the hello-numpy-sag example app first?
(https://github.com/NVIDIA/NVFlare/tree/main/examples/hello-numpy-sag)

**Comment by Nintorac** [comment]
This was due to memory errors on the server when starting the application

**Comment by YuanTingHsieh** [comment]
If you find the answer, should we close this issue?

**Comment by Nintorac** [comment]
Might be a better UX to get some sort of error from the admin in this case rather than just a timeout?

**Comment by YuanTingHsieh** [comment]
sure, I open an issue to track that enhancement: https://github.com/NVIDIA/NVFlare/issues/256
