### ISSUE TITLE
Cloud based dashboard should start automatically after instance reboot 

### ISSUE THREAD

**Issue by dirkpetersen** [NVIDIA/NVFlare#2556]
Some users may feel inclined to reboot or stop the dashboard server when they don't need it, so the dashboard container should start up after reboot. I am executing this as user ubuntu to ensure that the dashboard starts after a reboot or cold start 

```
(crontab -l 2>/dev/null; echo "@reboot \$HOME/.local/bin/nvflare dashboard --start -p 443 -f \$HOME > /var/tmp/nvflare-docker-start.log 2>&1") | crontab
```

**Comment by YuanTingHsieh** [comment]
Thanks for sharing your experience!

To clarify, you mean you have a ubuntu machine that runs "nvflare dashboard"
And you are showing if this machine is reboot, this command "nvflare dashboard" will be run automatically?

**Comment by dirkpetersen** [comment]
That’s correct, thank you

**Comment by YuanTingHsieh** [comment]
Thanks for sharing your script! Other users can use it when they have same use cases.
