### ISSUE TITLE
[BUG] Single quotes in organization name are not escaped properly 

### ISSUE THREAD

**Issue by dirkpetersen** [NVIDIA/NVFlare#2560]
An Org Admin registered with an organization name "Ben's Site". Unfortunately the single quote / apostrophe is not properly escaped and when I startup the client with /var/tmp/cloud/startup/start.sh I get this 

```
PYTHONPATH is /local/custom:
/var/tmp/cloud/startup/sub_start.sh: line 82: unexpected EOF while looking for matching `"'
/var/tmp/cloud/startup/sub_start.sh: line 88: syntax error: unexpected end of file
```

The org name is not escaped and changing "Ben's" to "Ben\\'s" did the trick

```
grep "Ben's" sub_start.sh
((python3 -u -m nvflare.private.fed.app.client.client_train -m $DIR/.. -s fed_client.json --set secure_train=true uid=AWS-T4 org=Ben's site config_folder=config 2>&1 & echo $! >&3 ) 3>$DIR/../pid.fl )
```

**Comment by YuanTingHsieh** [comment]
Thanks for raising this issue, @IsaacYangSLA can you check if we can support this scenario? thanks

**Comment by IsaacYangSLA** [comment]
Thanks for reporting the issue.  The issue might be related to how to allow special characters in different places.  As a quick fix, we can escape that in shell scripts.
