### ISSUE TITLE
Expose negate_key_metric argument in Job API.

### ISSUE THREAD

**Issue by holgerroth** [NVIDIA/NVFlare#2585]
This is different, what metrics you pass in vs. how best model selector behaviors

for example if the metrics is "accuracy", or "auc"

     the best model selection criteria will be   metrics_new > metrics_old

if the metrics is "loss" 
     the best model selection criteria will be   metrics_new  <  metrics_old

Does best model selection handle these ? how does the model know metrics criteria to use (> or <) for given metrics name ?

_Originally posted by @chesterxgchen in https://github.com/NVIDIA/NVFlare/pull/2563#discussion_r1604001458_

**Comment by YuanTingHsieh** [comment]
Currently, our Job API wraps several components but does not always provide a way to pass arguments for individual components. We will address this issue for all components.

One idea is to implement methods like "list_components" and "set_component_args," which would allow each "Job" object to report its components and set the arguments for its members.
