### ISSUE TITLE
stop_fl.sh does not terminate client side worker process

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#279]
The stop_fl.sh just does `touch shutdown.fl` , wait 5 seconds, then kill the process of pid.fl.

The worker process of client is not killed / terminated.

Steps to reproduce:
1. Launch server (start.sh)
2. Launch client (start.sh)
3. Using Admin: Upload app
4. Using Admin: Deploy app
5. Using Admin: Start app
6. Use stop_fl.sh

**Comment by chesterxgchen** [comment]
@YuanTingHsieh @yhwen can you handle this.
