### ISSUE TITLE
[BUG] Package conflict issue when installing flower and nvflare

### ISSUE THREAD

**Issue by hwpang** [NVIDIA/NVFlare#2810]
**Describe the bug**
I am trying to run the `hello-flower` example at `NVFlare/examples/hello-world/hello-flower`. I run `pip install -r requirements.txt`, but run into conflicting dependency issues. Please see below for the error trace.

**To Reproduce**
1. Go to `NVFlare/examples/hello-world/hello-flower`
2. Make a clean, empty environment. I use `conda create --name=nvflare_env python=3.10`
3. Install requirements with `pip install -r requirements.txt`

**Expected behavior**
Expected to install packages without issues.

**Screenshots**
```
INFO: pip is still looking at multiple versions of flwr to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1) and flwr because these package versions have conflicting dependencies.

The conflict is caused by:
    nvflare 2.5.0rc1 depends on protobuf==4.24.4
    flwr 1.10.0 depends on protobuf<5.0.0 and >=4.25.2
    nvflare 2.5.0rc1 depends on protobuf==4.24.4
    flwr 1.9.0 depends on protobuf<5.0.0 and >=4.25.2
    nvflare 2.5.0rc1 depends on protobuf==4.24.4
    flwr 1.8.0 depends on protobuf<5.0.0 and >=4.25.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.10
 - NVFlare Version: 2.5.0rc1

**Additional context**

**Comment by hwpang** [comment]
I tried switching to the newest main branch and did `pip install ./jobs/hello-flwr-pt/app/custom` as instructed in `NVFlare/examples/hello-world/hello-flower/README.md`, and got a different error:

```
Processing ./jobs/hello-flwr-pt/app/custom
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of flwr-pt to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement flwr<2.0,>=1.11.0 (from flwr-pt) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 1.0.0a0, 1.0.0rc0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0)
ERROR: No matching distribution found for flwr<2.0,>=1.11.0
```

**Comment by berryfanta** [comment]
`flwr-nvflare` integration is relatively new, my guess is that the stable releases have not yet caught up with the example. i suggest you try the nightly/source versions.

your error indicates:
1. nvflare protobuf and flwr protobuf requirements are not compatible
2. there does not exist a stable `flwr>=1.11.0`

here is a solution:

**Install nvflare from source**
- `git clone https://github.com/NVIDIA/NVFlare.git`
- `cd NVFlare`
- modify following line
https://github.com/NVIDIA/NVFlare/blob/b9c1c29f699c73c8b2d5dbace8d2aa1a5c7b0674/setup.cfg#L28
to: `protobuf==4.25.4`
- `pip install  .`

**Install flower nightly**
- `pip install flwr-nightly`
https://github.com/NVIDIA/NVFlare/blob/b9c1c29f699c73c8b2d5dbace8d2aa1a5c7b0674/examples/hello-world/hello-flower/jobs/hello-flwr-pt/app/custom/pyproject.toml#L10-L15
to
```
dependencies = [
    "torch==2.2.1",
    "torchvision==0.17.1",
]
```
**Then follow the `hello-flower` instructions as normal**
`cd...`
`pip install ./jobs/hello-flwr-pt/app/custom`
`...`

Not sure what downstream errors this hacked solution may cause though. Only concern from my perspective are the protobuf dependencies, but that could be a major difference for how communications are being handled. Maybe @yanchengnv can confirm

**Comment by yanchengnv** [comment]
Yes, this feature is still under development, as we speak. Once Flower and Flare versions become stable, we'll update the examples. Thanks for your interest!

Thanks for pointing out potential protobuf version conflict. We'll make sure it's resolved.
