### ISSUE TITLE
[BUG] FlowerJob is not generic enough: has hard dependency on torch and tensorboard

### ISSUE THREAD

**Issue by rfilgueiras** [NVIDIA/NVFlare#2962]
**Describe the bug**
I tried to use the [FlowerJob](https://github.com/NVIDIA/NVFlare/blob/aa4a0de6e190c9acf09f9a2eafc9b09b7214ed0f/nvflare/app_opt/flower/flower_job.py#L31) class to run the [Flower Pandas quickstart](https://github.com/adap/flower/tree/main/examples/quickstart-pandas) example.

**To Reproduce**
1. Create a Python virtual env with Python 3.10
2. Install: NVFlare 2.5.0, Flower 1.11.1, and [Flower Pandas Quickstart example ](https://github.com/adap/flower/tree/main/examples/quickstart-pandas) on the virtual env
3. Launch the Flower job using the [job.py](https://github.com/NVIDIA/NVFlare/blob/aa4a0de6e190c9acf09f9a2eafc9b09b7214ed0f/examples/hello-world/hello-flower/job.py) provided in the NVFlare Flower Hello World
4. Exceptions will be raised, one after another because the required dependencies are not installed:
- first because torch
- then because  tensorboard

This also happens if you try to run the [flwr-pt](https://github.com/NVIDIA/NVFlare/tree/aa4a0de6e190c9acf09f9a2eafc9b09b7214ed0f/examples/hello-world/hello-flower/flwr-pt) because tensordboard is required by the FlowerJob class but not specified in the pyproject.toml of the package.

Exceptions raised:
```py
ModuleNotFoundError: No module named 'torch'
ModuleNotFoundError: No module named 'tensorboard'
```

This happens because the [TBAnalyticsReceiver](https://github.com/NVIDIA/NVFlare/blob/aa4a0de6e190c9acf09f9a2eafc9b09b7214ed0f/nvflare/app_opt/tracking/tb/tb_receiver.py#L47) is imported by the FlowerJob.

**Expected behavior**

The base FlowerJob should not be so opinionated and should not require the analytics to be imported when not used.

Following the suggestion in the documentation: extend the FedJob implementation by creating a subclass.

A new subclass of the FlowerJob called FlowerPyTorchJob (for example) could have this hard requirement instead of the base class.

**Desktop (please complete the following information):**
 - OS: ubuntu 24.04
 - Python Version: 3.10 (venv)
 - NVFlare Version: 2.5

**Comment by YuanTingHsieh** [comment]
@rfilgueiras thanks for the feedback!
Great suggestions, I will look into this.

**Comment by YuanTingHsieh** [comment]
@rfilgueiras thanks for the suggestion, we merged the PR with the changes as you suggested
