### ISSUE TITLE
Do we need host / port / server_cn in AdminAPI anymore?

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#307]
Since we are passing OverseerAgent into the AdminAPI, should we be getting these info from the OverseerAgent?

As @nvkevlu pointed out:

- If we are going to keep backward compatibility, we will need to keep them
- If we are not going to worry about backward compatibility at all and require an OverseerAgent for AdminAPI, then we can get rid of them

**Comment by chesterxgchen** [comment]
@nvkevlu  can you handle this

**Comment by nvkevlu** [comment]
In dev-2.1, these are set as None and not used by anything calling AdminAPI anymore.
