### ISSUE TITLE
Multi-process executor's assumption

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#338]
https://github.com/NVIDIA/NVFlare/blob/main/nvflare/app_common/executors/multi_process_executor.py#L151

It only works if the prefix "self.get_multi_process_command()" return a command that can accept the "-m nvflare.private.fed.app.client.sub_worker_process"

~~And would treat it as "python -m nvflare.private.fed.app.client.sub_worker_process".~~

I wonder how this apply to other frameworks than PyTorch.

**Comment by YuanTingHsieh** [comment]
Thanks for the reply.

My question should be that if the user has some running commands that are not using Python.

Then "-m XXX" will not work for them.

**Comment by chesterxgchen** [comment]
The underline structure might be changed in the future release. Let me close this discussion
