### ISSUE TITLE
Print warning if unsupported python version is used

### ISSUE THREAD

**Issue by vladmihaisima** [NVIDIA/NVFlare#521]
Currently the documentation specifies "NVIDIA FLARE requires Python 3.8"(https://nvidia.github.io/NVFlare/installation.html). 

It would be great if the code would print a similar warning in case any nvflare component (server, client, etc.) ends up being started with the wrong python version. This will help new users that either missed the documentation or mistakenly start on the wrong version.

**Comment by chesterxgchen** [comment]
I think we should be able to do this. we will try to address this

**Comment by chesterxgchen** [comment]
ticket is closed, the check will be available in next release
