### ISSUE TITLE
Create owner project.yml error

### ISSUE THREAD

**Issue by holiday01** [NVIDIA/NVFlare#631]
I created a project.yml file and runed it by provision -p "".
The project.yml is following from https://nvidia.github.io/NVFlare/user_guide/provisioning_tool.html?highlight=project%20yml
The error show above
ValueError: client site1's org xxxx not defined in AuthPolicy
ValueError: client site2's org xxxx not defined in AuthPolicy
ValueError: client server's org xxxx not defined in AuthPolicy
ValueError: client admin's org xxxx not defined in AuthPolicy

**Comment by holiday01** [comment]
> Make sure to also specify the org further down the project.yml file.
> 
> ```yaml
> participants:
>   - name: ...
>     org: <my_org>    <-------
> 
> builders:
>   - ...
>   - path: nvflare.lighter.impl.auth_policy.AuthPolicyBuilder
>     args:
>       orgs:
>         <my_org>:    <-------
>           - relaxed
> ```

It is done.

**Comment by holiday01** [comment]
Where I can read the detail about set of each line from project.yml?

**Comment by holiday01** [comment]
A new error I got while I bash server/startup/start.sh

E0602 10:38:02.562101740  608351 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

**Comment by holiday01** [comment]
> This page currently contains the information about the provisioning system: https://nvidia.github.io/NVFlare/user_guide/provisioning_tool.html (although the docs site will soon be changing with the 2.1.0 release).
> 
> The builders are actually highly customizable so that you could change the code and have your own arguments. The default builders are included as a reference implementation but you could do almost anything you want by adding additional custom builders.
> 
> The AuthPolicyBuilder is unique in that it is used for authorization, so it needs to be set up in a way that is consistent with the orgs of the participants provisioned for the project.

I h

**Comment by nvkevlu** [comment]
> A new error I got while I bash server/startup/start.sh
> 
> E0602 10:38:02.562101740 608351 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

This error has happened before when system updates occur and the SSL version is mismatched. Usually, just rebooting the system fixes this.

**Comment by holiday01** [comment]
> > A new error I got while I bash server/startup/start.sh
> > E0602 10:38:02.562101740 608351 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
> 
> This error has happened before when system updates occur and the SSL version is mismatched. Usually, just rebooting the system fixes this.

It is not working after rebooting the machine. What is the information I can provide to fix it?
