### ISSUE TITLE
[CICD] Migrate to Blossom-ci

### ISSUE THREAD

**Issue by YanxuanLiu** [NVIDIA/NVFlare#649]
Blossom-ci pre-merge pipeline runs well. It's time to migrate from self-hosted runner CI to blossom-ci gradually. 
We divided the migration into the following stages:

- [x] Enable blossom-ci as an optional PR check (manual trigger required) and let it run for a few weeks
- [ ] Switch self-hosted runner CI as an optional check, and blossom-ci as required one
- [ ] remove self-hosted runners and related workflow files to meet security requirements
- [ ] blossom-ci for pre-merge only

@chesterxgchen @YuanTingHsieh Could you help to confirm the timelines and completion conditions for each stage?
cc @pxLi

**Comment by YuanTingHsieh** [comment]
These stages LGTM, what do you think @chesterxgchen
