### ISSUE TITLE
Admin API get_connected_client_list() includes the table heading "CLIENT" in results

### ISSUE THREAD

**Issue by parkeraddison** [NVIDIA/NVFlare#753]
When using the python admin api to `get_connected_client_list()`, the reply details includes the table header "CLIENT" with the actual results:
```
>>> adm.api.get_connected_client_list()
{'status': <APIStatus.SUCCESS: 'SUCCESS'>, 'details': {<FLDetailKey.CONNECTED_CLIENTS: 'connected_clients'>: ['CLIENT', 'site2', 'site1']}}
```

Straightforward fix --

There's a small mismatch in the column headers hardcoded in two files. The column header is defined as "Client" in the following (.upper gets called elsewhere): https://github.com/NVIDIA/NVFlare/blob/65848ff5ecdac29b26ca1a448f2106e06cda1d23/nvflare/private/fed/server/training_cmds.py#L589
however the admin api function is trying to filter out "CLIENT NAME" instead: https://github.com/NVIDIA/NVFlare/blob/99c199e2ed2b737a939114e23d4c4b765e71e0c3/nvflare/fuel/hci/client/fl_admin_api.py#L769-L776

Hope this helps!

**Comment by nvkevlu** [comment]
Thank you for pointing this out, we will take a look and fix this.
