### ISSUE TITLE
Error when trying to load a previously trained model to the server

### ISSUE THREAD

**Issue by ctestagrose** [NVIDIA/NVFlare#764]
I have a model that I have trained on data a few months ago that I would like to load to the server. I am receiving the following error when attempting to start the server.
```
ServerRunner - ERROR - [run=1]: Aborting current RUN due to FATAL_SYSTEM_ERROR received: expect model to be torch.nn.Module but got <class 'model_def.ModelDefinition'>
```
The model uses the torchvision Inception-V3 model with additional layers added. See below:

```
model = models.inception_v3(pretrained=False)
        model.fc = nn.Sequential(
            nn.Linear(model.fc.in_features, 1024),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(1024, 4))
        model.aux_logits = False
```

This model is defined in a separate model_def.py file in the respective folder in the following fashion:
```
from torchvision import models
import torch.nn as nn
import torch

class ModelDefinition():
    def __init__(self):
        self.model = models.inception_v3(pretrained=False)
        self.model.fc = nn.Sequential(
            nn.Linear(self.model.fc.in_features, 1024),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(1024, 4))
        self.model.aux_logits = False

    def forward(self, x):
        x = self.model(x)
        return x

```

I placed the previously saved .pth model in the respective folder and modified the persistor section of the server_config file. See below:

```
  "components": [
    {
      "id": "persistor",
      "name": "PTFileModelPersistor",
      "args": {
        "model": {
			"path": "model_def.ModelDefinition"
	    },
		"source_ckpt_file_full_name": "/code/models/best_model.pth"
      }
	},
```

How do I go about loading this model? Would I need to create my own persistor.py file to carry this out or is my approach to performing this incorrect? 

Thank you for your help.

**Comment by ctestagrose** [comment]
I seem to have resolved the error by adding calling the nn.Module super class as so:
```
class ModelDefinition(nn.Module):
    def __init__(self):
        super().__init__()
```

**Comment by YuanTingHsieh** [comment]
@ctestagrose thanks for providing the problem you encountered and the solution you found!

Please let us know if you have any other questions, thanks!
