### ISSUE TITLE
`relay_and_wait` does not pass on Shareable header information

### ISSUE THREAD

**Issue by holgerroth** [NVIDIA/NVFlare#776]
The cyclic workflow sets the value [here](https://github.com/NVIDIA/NVFlare/blob/4fa2343819bba12e219f4f2587d293ed8492bb1a/nvflare/app_common/workflows/cyclic_ctl.py#L123) but it seems to get lost during relay_and_wait. A Learner uses for example `current_round = shareable.get_header(AppConstants.CURRENT_ROUND)` would receive *None* at the 2nd client to whom the shareable is relayed to.

**Comment by YuanTingHsieh** [comment]
I think it might be related to this portion of code:

https://github.com/NVIDIA/NVFlare/blob/dev/nvflare/app_common/workflows/cyclic_ctl.py#L92-L103

```
    def _process_result(self, client_task: ClientTask, fl_ctx: FLContext):
        # submitted shareable is stored in client_task.result
        # we need to update task.data with that shareable so the next target
        # will get the updated shareable
        task = client_task.task

        # update the global learnable with the received result (shareable)
        # e.g. the received result could be weight_diffs, the learnable could be full weights.
        self._last_learnable = self.shareable_generator.shareable_to_learnable(client_task.result, fl_ctx)

        # prepare task shareable data for next client
        task.data = self.shareable_generator.learnable_to_shareable(self._last_learnable, fl_ctx)

```

@IsaacYangSLA do we lost this info in this function?

**Comment by yanchengnv** [comment]
Yes, all we need to do here is to add:

task.data.set_header(AppConstants.CURRENT_ROUND, self._current_round)

On the other hand, I'm thinking perhaps we need to keep all headers from the original task, even though now CURRENT_ROUND is the only header for this case.

We probably need a simple function in the Shareable class: 

def copy_headers_from(source: Shareable)

**Comment by yanchengnv** [comment]
BTW, I will take care of this for 2.2, so Isaac can focus on other priorities.
