### ISSUE TITLE
NVFlare python version not compatible with Google colab or Google Vertex AI Notebooks

### ISSUE THREAD

**Issue by filipmu** [NVIDIA/NVFlare#78]
NVFlare requires python 3.8.10 or higher per the pypi page, and both Google Colab and Google Vertex AI Notebooks currently run python 3.7.12 and 3.7.10 respectively.  Upgrading these environments is relatively undocumented and complex.  

For reference PyTorch 1.10 works with python 3.5 or greater.

Can the dependencies on python 3.8.10 be reduced so that python 3.7 will suffice?

**Comment by nvkevlu** [comment]
Unfortunately right now NVFlare does not work on python 3.7 and there are currently no plans to reduce the dependencies on python 3.8 although there are plans to make NVFlare compatible with python 3.9 in the future. Hopefully Google Colab and Google Vertex AI can be upgraded to run on python 3.8 soon.

**Comment by filipmu** [comment]
OK, that's too bad.  Its going to be hard to influence Google's plans.  Also, this makes it difficult to use nvflare on Jetson, since the NVIDIA L4T ML container on NGC is on python 3.6.

I tried building with 3.7 and found 12 files that had issues - walrus operators and fstring formatting were flagged as syntax errors.  Are there other behind the scenes capabilities used from python 3.8?

**Comment by nvkevlu** [comment]
We will look into this and see what we can do about it.

**Comment by YuanTingHsieh** [comment]
I forgot to mention, thanks for raising this good issue!

**Comment by YuanTingHsieh** [comment]
Closing this issue as the original question "Can the dependencies on python 3.8.10 be reduced so that python 3.7 will suffice?" is resolved.

The answer is yes now.
