### ISSUE TITLE
Support Python versions >3.8

### ISSUE THREAD

**Issue by taleinat** [NVIDIA/NVFlare#782]
Python 3.8 was released on October 2019, nearly 3 years ago. Since then 3.9 and 3.10 have been released, and 3.11 is planned to be released later this year. 3.8 and 3.9 only receive security-related fixes, and 3.8 will only be supported in this way until October 2024.

[More info about supported Python versions](https://devguide.python.org/versions/#supported-versions).

The latest versions of important libraries are likely to begin dropping support for Python 3.8. For example:
* The latest versions of Pandas (1.4.3) and NumPy (1.23.2) require Python >= 3.8.
* The latest versions of PyTorch (1.12.1) and Tensorflow (2.9.1) require Python >= 3.7.

It would be good to support newer versions of Python, starting with 3.9 and 3.10.

**Comment by YuanTingHsieh** [comment]
Thanks @taleinat , this is a good suggestion.

We definitely need to do this, we will try to add these support ASAP.
