### ISSUE TITLE
Don't have file or function named 'segimage2itkimage'

### ISSUE THREAD

**Issue by Zhouziyuya** [NVIDIA/NVFlare#806]
The path 'NVFlare/examples/prostate/data_preparation/utils/' don't have the file 'segimage2itkimage' and this will cause the 'NVFlare/examples/prostate/data_preparation/data_conversion_PROSTATEx.sh' error when running.

**Comment by YuanTingHsieh** [comment]
@ZiyueXu77 can you take a look at this? thanks!

**Comment by ZiyueXu77** [comment]
@Zhouziyuya, this function is part of an external library, please see our readme: "Further, [dcmqi](https://github.com/qiicr/dcmqi) is used to convert DICOM segmentations to NIfTI format by using the [segimage2itkimage](https://qiicr.gitbook.io/dcmqi-guide/opening/cmd_tools/seg/segimage2itkimage#segimage2itkimage) function, download the binary to ./utils folder."

**Comment by Zhouziyuya** [comment]
> 

okok, I have download this file from this github link https://github.com/QIICR/dcmqi/releases. Aan thank you very much!
