### ISSUE TITLE
Unknown client show from admin shell

### ISSUE THREAD

**Issue by holiday01** [NVIDIA/NVFlare#822]
I opened a server. No clients start, but the admin shows the "CLIENT" by check status server.
![image](https://user-images.githubusercontent.com/20851973/188073772-7561e5c7-59a3-4367-890f-bdc839955ce1.png)

After I remove those clients, they will restart to show in the admin shell.

**Comment by YuanTingHsieh** [comment]
Hi @holiday01 

Thanks for raising an issue.

What version of NVFlare are you using?
What environment are you running on?

I am guessing you have previous clients that have not been stopped properly.

Can you do something like `pkill -9 -f "nvflare"` on your computer to make sure all the NVFlare processes are stopped?

Then you start your server, you should see no clients connected.

**Comment by holiday01** [comment]
Thank you. The cmd kill worked. I used the shutdown client and server, but the admin process was not killed. Right?

**Comment by holiday01** [comment]
It is disappeared again.
Re-activate dead client:site-3 with token:
I had killed all process "nvflare".
site-3 is no reply from admin
