### ISSUE TITLE
[BUG] Tenseal necessary, makes installation impossible on Apple Silicon.

### ISSUE THREAD

**Issue by siomvas** [NVIDIA/NVFlare#913]
As discussed in #130 tenseal remains unavailable for Apple Silicon. The current NVFlare version (2.2.0) has no optional features and tenseal is necessary, making installation impossible on Apple Silicon.

**Comment by YuanTingHsieh** [comment]
thanks @siomvas for raising this issue, this fix will be in next release as #920 is merged
