### ISSUE TITLE
Dependency error for teanseal==0.3.0

### ISSUE THREAD

**Issue by imadeit** [NVIDIA/NVFlare#946]
Hi, I am trying to run the sample as follows:
https://github.com/NVIDIA/NVFlare/tree/dev/integration/monai/examples/spleen_ct_segmentation

But when I try to install dependent packages, the following error prevents me from moving forward.
ERROR: Could not find a version that satisfies the requirement tenseal==0.3.0 (from nvflare) (from versions: none)
ERROR: No matching distribution found for tenseal==0.3.0

The version of tenseal is quite old and it seems it is the dependency from NVFlare, could this be fixed?

**Comment by holgerroth** [comment]
Hi @imadeit, thanks for reaching out. There's no dependency for tenseal in this example. The dependency comes from the nvflare package itself. You should be able to install tenseal from pypi though https://pypi.org/project/tenseal/#history

FYI, for the next release we are planning to make the tenseal installation optional https://github.com/NVIDIA/NVFlare/pull/920

You might be able to install nvflare from the dev branch if you cannot get it to work otherwise. `pip install -e $NVFLARE_HOME`, where NVFLARE_HOME is the root folder of the repo.

**Comment by imadeit** [comment]
Thanks @holgerroth 
I tried to install through pypi, it seems not working properly as above, I am running in virtualenv proposed in the repo.
NVFlare/integration/monai/examples/spleen_ct_segmentation$ pip install tenseal==0.3.0
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement tenseal==0.3.0 (from versions: none)
ERROR: No matching distribution found for tenseal==0.3.0

Without tenseal, can not install nvflare, then can not run the sample.
Any methods that can workaround?

**Comment by holgerroth** [comment]
Which environment are you on (Linux/Windows)? I can install 0.3.0 fine with pip --version is 22.2.2. Maybe you need to upgrade pip?

As stated above, you can install nvflare from source without tenseal using `pip install -e $NVFLARE_HOME`.  @IsaacYangSLA might be able to give more details.

**Comment by YuanTingHsieh** [comment]
@imadeit 

Let's assume you clone the NVFlare repo to ~/NVFlare.
After you activate your virtualenv (source venv/bin/activate).
You can install nvflare directly via this command:
```
pip install -e ~/NVFlare
```

**Comment by imadeit** [comment]
Thanks for advice.
I am able to run pip install -e ${NVFlare}
My real problem is that when I try the sample: https://github.com/NVIDIA/NVFlare/tree/dev/integration/monai/examples/spleen_ct_segmentation
Especially  when I run 4.1, there is an exception as follows:
exception: No module named 'monai_nvflare'
Though I have run pip install above, the sample still complains,
then I tried: pip install monai_nvflare
The tenseal 0.3.0 dependency error happened.
If you have confirmed the sample is workable in your environments, then probably it is my env's problem (Ubuntu 20.04 LTS, pip 22.2.2, python3.8).

**Comment by holgerroth** [comment]
Right. Then you also have to install monai_nvflare from source, see [here](https://github.com/NVIDIA/NVFlare/tree/dev/integration/monai#requirements).

**Comment by holgerroth** [comment]
You can remove the nvflare dependency here if you have it already installed https://github.com/NVIDIA/NVFlare/blob/ca9183fcc8cb5a309bfce9f9ea2e4814c4c9030c/integration/monai/setup.py#L58

**Comment by imadeit** [comment]
By disabling the dependency and after several try of installing dependent libraries, the above example starts to train.
Hope such kind of tedious work would be solved for new users in the future, I may think that medical experts do not have so much IT skills to debug.
Thanks.
