### ISSUE TITLE
[BUG] Passing Relative Path to Simulation leads to nested file path and run error

### ISSUE THREAD

**Issue by mgechols** [NVIDIA/NVFlare#980]
**Describe the bug**
When running nvflare simulate, if passing a relative path to the workspace directory the system will create a duplicate-nested workspace to store the 'simulate_job' directory. This causes the simulation to be unable to find the configuration files and results in an 'ClientTaskWorker - ERROR - ClientTaskWorker run error. PATH/TO/simulate_job/app_site-*/config/config_fed_client.json is not a valid file' error.

**To Reproduce**
1. Go to /rootdirectory command line
2. Type nvflare simulator -w relative/path/not/to/root -n 2 -t 2 path/to/app
3. See error

** To Fix**
Provide absolute path to the generated workspace directory instead of a relative path inside of root.

**Expected behavior**
Simulation runs.

**Desktop (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Python Version [3.8]
 - NVFlare Version [2.2.0]

**Comment by yhwen** [comment]
We provide two ways to provide the workspace path. It can be ab absolute path, or a relative path. If it's a relative path, it needs to be the path where you run the simulator.

**Comment by YuanTingHsieh** [comment]
@mgechols thanks for raising the issue!
@yhwen will submit a fix ASAP.

**Comment by yhwen** [comment]
Fixed in https://github.com/NVIDIA/NVFlare/pull/985
